default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: tee_shits_development
  username: tee_shits_db
  password: NMDBadmin123!

test:
  <<: *default
  database: tee_shits_test
  username: tee_shits_db
  password: NMDBadmin123!

production:
  <<: *default
  username: tee_shits_db
  password: NMDBadmin123!
  database: tee_shits_production
