default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: nice_marmot_development
  username: nice_marmot_db
  password: NMDBadmin123!

test:
  <<: *default
  database: nice_marmot_test
  username: nice_marmot_db
  password: NMDBadmin123!

production:
  <<: *default
  host: localhost
  username: nice_marmot_db
  password: NMDBadmin123!
  database: nice_marmot_production
