default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: nice_marmot_development
  username: nice_marmot_db
  password: NMDBadmin123!

test:
  <<: *default
  database: nice_marmot_test
  username: nice_marmot_db
  password: NMDBadmin123!

production:
  <<: *default
  username: nice_marmot_db
  password: NMDBadmin123!
  database: nice_marmot_production
